<?php
$id = '';
$data_melisKey = '';

if (!empty($this->id))
    $id = ' id="' . $this->id . '"';

if (!empty($this->melisKey))
    $data_melisKey = ' data-meliskey="' . $this->melisKey . '"';

?>
<div id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
    <div class="modal fade" id="modal-site-translation">
        <div class="modal-dialog" role="documentxxxx">
            <div <?php echo $id.' '.$data_melisKey; ?> class="modal-content"></div>
        </div>
    </div>
</div>