<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];
$data_melisKey = $this->melisKey;
?>
<div class="modal-content">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="nav-item active">
                            <a data-bs-target="#<?php echo $this->zoneconfig['conf']['id'] ?>" href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons notes" data-bs-toggle="tab"
                               aria-expanded="true"><i></i><?php echo $this->zoneconfig['conf']['name']; ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" id="<?= $id ?>">
                            <div class="row">
                                <div class="col-md-12" id="duplicateTree">
                                    <p class="modal-text-info"><?= $this->translate('') ?> </p>
                                    <?php
                                    echo $this->form()->openTag($this->form);
                                    echo $this->melisFieldCollection($this->form);
                                    echo $this->form()->closeTag(); ?>
                                    <script type="text/javascript">
                                        $(function() {
                                            melisCore.loadCustomCheckboxElement();
                                        });
                                    </script>
                                    <br>
                                    <div class="footer-modal d-flex flex-row justify-content-between">
                                        <button data-bs-dismiss="modal" class="btn btn-danger float-left">
                                            <i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscms_menu_cancel') ?>
                                        </button>
                                        <button class="btn btn-success" id="duplicatePageTree" data-style-id="<?= $this->styleId ?>">
                                            <i class="fa fa-save"></i> <?php echo $this->translate('tr_meliscms_page_tree_save') ?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
