<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="tab-content innerAll spacing-x2"
    style="margin-bottom: 50px;"
>
    <?php
        if (! empty($this->zoneconfig['interface'])) {
            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    ?>
</div>