<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="<?= ($this->isHidden) ? '' : '' ?>"
    style="position: relative;"
>
    <div
        id="accordion"
        class="accordion-group"
    >
        <div class="card">
            <?php
                if (! empty($this->zoneconfig['interface'])) {
                    foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                        echo $this->$keyConfig;
                    }
                }
            ?>
        </div>
    </div>
</div>
