<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="panel-collapse show"
>
    <div class="card-body">
        <div class="spacing-x2 innerAll" style="margin-bottom: 50px;">
            <div class="row">
                <?php
                    if (! empty($this->zoneconfig['interface'])) {
                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                            echo $this->$keyConfig;
                        }
                    }
                ?>
            </div>
        </div>
    </div>
</div>