<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="tab-pane container-level-a"
>
    <div class="accordion-group" id="accordion">
        <div class="card" >
            <?php
                if (! empty($this->zoneconfig['interface'])) {
                    foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                        echo $this->$keyConfig;
                    }
                }
            ?>
        </div>
    </div>
</div>