<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="<?= ($this->isHidden) ? 'hidden' : '' ?>"
>
    <?php
        if (! empty($this->zoneconfig['interface'])) {
            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    ?>
</div>
