<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
    class="card-heading mini-template-menu-manager-tool-header"
>
    <div class="card-title" style="margin-top: inherit; margin-bottom: 0;">
        <a class="accordion-toggle" data-bs-toggle="collapse" data-bs-target="#id_meliscms_mini_template_menu_manager_tool_body">
            <h1 class="content-heading"><?= $this->translate('tr_meliscms_mini_template_menu_manager_tool') ?>
                <span class="custom-mtpl-desc"><?= $this->translate('tr_meliscms_mini_template__menu_manager_tool_header_sub_title') ?></span>
            </h1>
        </a>
    </div>
</div>