<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    class="me-heading bg-white border-bottom"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
>
    <div class="row">
        <div class="me-hl col-xs-12 col-sm-8 col-md-9">
            <h1 class="content-heading"><?= $this->translate($this->zoneconfig['conf']['name']) ?></h1>
            <p><?= $this->translate('tr_meliscms_mini_template_manager_tool_header_sub_title') ?></p>
        </div>
        <div class="me-hr col-xs-12 col-sm-4 col-md-3">
            <?php
            if (! empty($this->zoneconfig['interface'])) {
                foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                    echo $this->$keyConfig;
                }
            }
            ?>
        </div>
    </div>
</div>