<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width">
        <div class="step2-forms">
            <div class="sites_step2-single-language">
                <?php
                $form = $this->step2_form_single_language;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <label class="err_site_selected_lang"><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_language'); ?><sup>*</sup>
                        <i class="fa fa-info-circle fa-lg float-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_languages tooltip')?>"></i>
                    </label>
                    <div class="row">
                        <?php
                        foreach($this->langList as $key => $val) {
                            $id = $val['lang_cms_id'].'-'.$val['lang_cms_locale'];
                            ?>
                            <div class="col-md-4">
                                <label class="melis-radio-box" for="<?= $id ?>">
                                    <input type="radio" value="<?= $id.'-'.$val['lang_cms_name'] ?>" name="site_selected_lang" id="<?= $id ?>" required="required"/>
                                    <?= $val['lang_cms_name']; ?>
                                    <span class="melis-radio-box-circle"></span>
                                </label>
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <?php
                echo $this->melisFieldCollection($form);
                echo $this->form()->closeTag();
                ?>
            </div>
            <div class="sites_step2-multi-language">
                <?php
                $form = $this->step2_form_multi_language;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <label class="err_site_selected_lang"><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_languages'); ?> <sup>*</sup>
                        <i class="fa fa-info-circle fa-lg float-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_languages tooltip')?>"></i>
                    </label>
                    <div class="row">
                        <?php
                        foreach($this->langList as $key => $val) {
                                $id = $val['lang_cms_id'].'-'.$val['lang_cms_locale'];
                            ?>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="checkbox cb-cont" style="position:relative">
                                        <label class="remember-me-cont">
                                            <span class="cbmask-outer clearfix">
                                                <span class="cbmask-inner cb-modules-mask"></span>
                                            </span>
                                            <input class="no-box-shadow" type="checkbox" value="<?= $id.'-'.$val['lang_cms_name'] ?>" name="site_selected_lang" id="<?= $id ?>" required="required" />
                                        </label>
                                        <span><?= $val['lang_cms_name']; ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <?php
                foreach ($form->getElements() As $key => $val)
                {
                    echo '<div class="form-group">';
                    if ($val->getLabel())
                    {
                        $required = '';
                        if(!empty($val->getAttribute('required'))){
                            $required = '<sup>*</sup>';
                        }
                        echo $this->formLabel()->openTag($val);
                        echo $val->getLabel();
                        echo $required;
                        ?>
                        <i class="fa fa-info-circle fa-lg float-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $val->getOption('tooltip'); ?>"></i>
                        <?php
                        echo $this->formLabel()->closeTag();
                    }
                    echo $this->formElement($val);
                    echo '</div>';
                }
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
