<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width">
        <div class="step4-forms">
            <div class="sites_step4-module">
                <?php
                $form = $this->step4_form_module;
                $form->prepare();
                echo $this->form()->openTag($form);
                foreach ($form->getElements() As $key => $val)
                {
                    $newId = '';
                    $hide = '';
                    if($key == "create_sites_file"){
                        $newId = "createSiteFiles";
                        $hide = 'hidden';
                        $val->setValue('yes');
                    }
                    echo '<div class="form-group '.$hide.'" id="'.$newId.'">';
                    if ($val->getLabel())
                    {
                        if($key == 'siteCreateModuleName') {
                            echo $this->formLabel($val);
                        }else{
                            $required = '';
                            if(!empty($val->getAttribute('required'))){
                                $required = '<sup>*</sup>';
                            }
                            echo $this->formLabel()->openTag($val);
                            echo $val->getLabel();
                            echo $required;
                            echo $this->formLabel()->closeTag();
                        }
                    }
                    echo $this->formElement($val);
                    echo '</div>';
                }
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
