<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width">
        <div class="step3-forms">
            <div class="sites_step3-single-domain">
                <?php
                $form = $this->step3_form_single_domain;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <?php
                echo $this->melisFieldCollection($form);
                echo $this->form()->closeTag();
                ?>
            </div>
            <div class="sites_step3-multi-domain">
                <?php
                $form = $this->step3_form_multi_domain;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <label for=""><?= $this->translate('tr_melis_cms_sites_tool_add_step3_multi_domain_name');?>
                        <i class="fa fa-info-circle fa-lg pull-right tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="<?= $this->translate('tr_melis_cms_sites_tool_add_step3_multi_domain_name tooltip')?>"></i>
                    </label>
                    <div id="multi-domains_container" class="tool-sites_container_fixed_width">
                        <!-- This is where the dynamic input fields loaded-->
                    </div>
                </div>
                <?php
                echo $this->melisFieldCollection($form);
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
