<?php
$data_melisKey = $this->melisKey;
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->siteId . '_' . $this->zoneconfig['conf']['id'] . '"';

?>

<div<?= $id; ?>  class="tab-pane container-level-a" data-melisKey='<?= $data_melisKey; ?>'>
    <?php
    if(empty($this->noAccess))
    {
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    }
    else
    {
        echo '<h4>'.$this->noAccess.'</h4>';
    }

    ?>
</div>
