<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width">
        <div class="step4-forms">
            <div class="sites_step4-module">
                <?php
                $form = $this->step4_form_module;
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->melisFieldCollection($form);
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
