<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div class="" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="step2-forms">
        <div class="sites_step2-single-language">
            <?php
            $form = $this->step2_form_single_language;
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
            <label><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_language'); ?></label>
            <div class="tool-sites_container_fixed_width">
                <div class="row">
                    <?php
                    foreach($this->langList as $key => $val) {
                        $id = $val['lang_cms_id'].'_'.$val['lang_cms_name'];
                        ?>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="radio" value="<?= $val['lang_cms_id']; ?>" name="site_selected_lang" id="<?= $id ?>"/> <label for="<?= $id ?>"><?= $val['lang_cms_name']; ?></label>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <?php
            echo $this->melisFieldCollection($form);
            echo $this->form()->closeTag();
            ?>
        </div>
        <div class="sites_step2-multi-language">
            <?php
            $form = $this->step2_form_multi_language;
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
            <label><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_languages'); ?></label>
            <div class="tool-sites_container_fixed_width">
                <div class="row">
                    <?php
                    foreach($this->langList as $key => $val) {
                            $id = $val['lang_cms_id'].'_'.$val['lang_cms_name'];
                        ?>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" value="<?= $id ?>" name="site_selected_languages" id="<?= $id ?>"/> <label for="<?= $id ?>"><?= $val['lang_cms_name']; ?></label>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="step2_sites-url">
                <label for=""><?= $this->translate('tr_melis_cms_sites_tool_add_step2_reflect_urls');?></label>
                <div class="form-group">
                    <input type="radio" name="sites_url_setting" id="sites_url-1" value="1"> <?= $this->translate('tr_melis_cms_sites_tool_add_step2_url_local_after_domain');?>
                </div>
                <div class="form-group">
                    <input type="radio" name="sites_url_setting" id="sites_url-2" value="2"> <?= $this->translate('tr_melis_cms_sites_tool_add_step2_url_different_domains');?>
                </div>
                <div class="form-group">
                    <input type="radio" name="sites_url_setting" id="sites_url-3" value="3"> <?= $this->translate('tr_melis_cms_sites_tool_add_step2_url_do_nothing');?>
                </div>
            </div>
            <?php
            echo $this->melisFieldCollection($form);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
