<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

?>

<div class="modal-content" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="modal-body padding-none" id="modal-site-creation">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons <?php echo ($this->id) ? 'pencil' : 'plus'?>" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_melis_cms_sites_tool_create'); ?></a></li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div id="siteAddAlert" class="alert alert-danger hidden"><strong></strong> <?= $this->translate('tr_melis_cms_sites_tool_add_create_site_required_field'); ?></div>
                    <div class="owl-carousel owl-theme owl-loaded sites-steps-owl">
                        <?php
                            if (!empty($this->zoneconfig['interface'])) {
                                $step = 1;
                                foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                                    echo  '<div data-step="step_'.$step.'" class="item">' . $this->$keyConfig . '</div>';
                                    $step++;
                                }
                            }
                        ?>
                    </div>
                    <div align="right">
                        <button type="button" data-dismiss="modal" class="btn btn-danger pull-left"><?php echo $this->translate('tr_meliscms_tool_sites_cancel')?></button>
                        <button type="button" class="btn btn-success" id="btn-prev-step"><?php echo $this->translate('tr_meliscms_tool_sites_prev') ?></button>
                        <button type="button" class="btn btn-success" id="btn-next-step"><?php echo $this->translate('tr_meliscms_tool_sites_next') ?></button>
                        <button type="button" class="btn btn-success" id="btn-finish-step"><?php echo $this->translate('Finish') ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
