<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width step-4-datas">
        <div class="form-group" tabindex="-1">
            <label class="err_site_selected_lang" tabindex="-1"><?= $this->translate('tr_melis_cms_sites_tool_add_step4_is_new_module'); ?>
                <i class="fa fa-info-circle fa-lg pull-right tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="<?= $this->translate('tr_melis_cms_sites_tool_add_step4_is_new_module tooltip'); ?>" data-container="body"></i>
            </label>
            <div id="is_create_new_module_for_site">
                <div class="row" tabindex="-1">
                    <div class="col-md-2" tabindex="-1">
                        <label class="melis-radio-box" for="create_module_yes" tabindex="-1">
                            <input type="radio" name="is_create_module" id="create_module_yes" value="yes" tabindex="-1">
                            <?= $this->translate('tr_meliscms_tool_sites_yes'); ?>
                        </label>
                    </div>
                    <div class="col-md-2" tabindex="-1">
                        <label class="melis-radio-box" for="create_module_no" tabindex="-1">
                            <input type="radio" name="is_create_module" id="create_module_no" value="no" tabindex="-1">
                            <?= $this->translate('tr_meliscms_tool_sites_no'); ?>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="step4-forms hidden">
            <div class="sites_step4-module">
                <?php
                $form = $this->step4_form_module;
                $form->prepare();
                echo $this->form()->openTag($form);
                foreach ($form->getElements() As $key => $val)
                {
                    echo '<div class="form-group '.$key.'">';
                    if ($val->getLabel())
                    {
                        $required = '';
                        if(!empty($val->getAttribute('required'))){
                            $required = '<sup>*</sup>';
                        }
                        echo $this->formLabel()->openTag($val);
                        echo $val->getLabel();
                        echo $required;
                        ?>
                        <i class="fa fa-info-circle fa-lg pull-right tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="<?= $val->getOption('tooltip'); ?>"></i>
                        <?php
                        echo $this->formLabel()->closeTag();
                    }
                    echo $this->formElement($val);
                    echo '</div>';
                }
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
