<?php

$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->siteId . '_' . $this->zoneconfig['conf']['id'] . '"';

$data_melisKey = $this->melisKey;
$status = '';

?>
<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
    <div class="spacing-x2 innerAll">
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="pull-left"><?= $this->translate('tr_melis_cms_sites_module_loading'); ?></h3>
                </div>
                <div class="col-md-6">
                    <div id="site-select-deselect-all-module" class="<?= $this->siteId ?>_main_switch make-switch " data-on-label="<?= $this->translate('tr_meliscore_common_active'); ?>" data-off-label="<?= $this->translate('tr_meliscore_common_inactive'); ?>" data-text-label="<?= $this->translate('tr_meliscore_tool_user_col_status'); ?>">
                        <input type="checkbox" <?= $status; ?> checked/>
                    </div>
                </div>
                <div class="switch-all-noti">
                    <div class="icon-cont clearfix">
                        <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="left" title="<?=$this->translate('tr_meliscore_module_management_select_deselect_all_module_noti'); ?>"></i>
                    </div>
                </div>
            </div>
        </div>
        <!-- modules -->
        <div class="module-settings">
            <div class="ms-heading">
                <div class="pull-left">
                    <h4 id="meliscore-tool-module-content-title"><?= $this->translate('tr_meliscore_module_management_modules'); ?></h4>
                </div>
                <div class="pull-right">
                    <div class="clearfix ms-cont">
                        <div class="row ">
                            <div class="col-md-6 col-sm-6 col-xs-6"><!--  module-version-display -->
                                <h4>Version </h4>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="icon-cont clearfix">
                                    <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="left" title="<?=$this->translate('tr_meliscore_module_management_notification_tip'); ?>"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <form>
                <div class="module-sortable">
                    <?php
                    if (!empty($this->modules))
                    {
                        foreach($this->modules as $moduleName => $moduleStatus)
                        {
                            ?>
                            <div class="module-cont clearfix">
                                <div class="pull-left">
                                    <h4><?= $moduleName; ?></h4>
                                </div>
                                <div class="pull-right">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-xs-6 ">
                                            <h4><?= isset($this->modulesInfo[$moduleName]['version']) ? $this->modulesInfo[$moduleName]['version'] : 'v1.0'; ?> </h4>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 ">
                                            <div data-siteModule-name="<?= $moduleName; ?>" class="make-switch <?= $this->siteId ?>_module_switch module-switch" data-on-label="<?= $this->translate('tr_meliscore_common_active'); ?>" data-off-label="<?= $this->translate('tr_meliscore_common_inactive'); ?>" data-text-label="<?= $this->translate('tr_meliscore_tool_user_col_status'); ?>">
                                                <?php
                                                $status = $moduleStatus > 0 ? 'checked' : '';
                                                ?>
                                                <input name="moduleLoad<?= $moduleName; ?>" data-siteModule-name="<?= $moduleName; ?>" type="checkbox" <?= $status; ?>/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <?php
                        }
                    }
                    ?>
                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        // initialize jquery sortable
        $(".module-sortable").sortable({
            containment: "parent",
            placeholder: "ui-sortable-placeholder",
            opacity: 0.8,
            revert: 300,
            tolerance: "pointer",
        });
    });
</script>