<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="tool-sites_container_fixed_width">
        <div class="step2-forms">
            <div class="sites_step2-single-language">
                <?php
                $form = $this->step2_form_single_language;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <label class="err_site_selected_lang"><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_language'); ?><sup>*</sup></label>
                <div class="row">
                    <?php
                    foreach($this->langList as $key => $val) {
                        $id = $val['lang_cms_id'].'-'.$val['lang_cms_locale'];
                        ?>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="radio" value="<?= $id.'-'.$val['lang_cms_name'] ?>" name="site_selected_lang" id="<?= $id ?>" required="required"/>
                                <label for="<?= $id ?>"><?= $val['lang_cms_name']; ?></label>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php
                echo $this->melisFieldCollection($form);
                echo $this->form()->closeTag();
                ?>
            </div>
            <div class="sites_step2-multi-language">
                <?php
                $form = $this->step2_form_multi_language;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <label class="err_site_selected_lang"><?= $this->translate('tr_melis_cms_sites_tool_add_step2_select_languages'); ?> <sup>*</sup></label>
                <div class="row">
                    <?php
                    foreach($this->langList as $key => $val) {
                            $id = $val['lang_cms_id'].'-'.$val['lang_cms_locale'];
                            $selected = ($val['lang_cms_locale'] == 'en_EN') ? 'checked' : '';
                        ?>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" value="<?= $id.'-'.$val['lang_cms_name'] ?>" name="site_selected_lang" id="<?= $id ?>" <?= $selected ?> required="required" /> <label for="<?= $id ?>" id=""><?= $val['lang_cms_name']; ?></label>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php
                foreach ($form->getElements() As $key => $val)
                {
                    echo '<div class="form-group">';
                    if ($val->getLabel())
                    {
                        $required = '';
                        if(!empty($val->getAttribute('required'))){
                            $required = '<sup>*</sup>';
                        }
                        echo $this->formLabel()->openTag($val);
                        echo $val->getLabel();
                        echo $required;
                        echo $this->formLabel()->closeTag();
                    }
                    echo $this->formElement($val);
                    echo '</div>';
                }
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
