<div id="siteaddalert"></div>

<div id="formsiteadd">
<?php 
$form = $this->meliscms_site_tool_generic_form;
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();

echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger pull-left'
    ), 'dismiss');
?>

<a class="btn btn-success pull-right" id="btnSiteAdd"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscms_template_save'); ?></a>
</div>