<div id="siteeditalert"></div>
<p class="modal-text-info"><?= $this->translate('tr_meliscms_tool_site_info') ?></p>
<?php 
    $form = $this->meliscms_site_tool_edition_form;
    echo $this->form()->openTag($form);
    echo $this->melisFieldCollection($form);
    echo $this->form()->closeTag();
?>
<div class="col-sm-12">
	<a href="#" class="small"  id="btnDelEnv">
		<i class="fa fa-times"></i> <?= $this->translate('tr_meliscms_tool_site_delete_env'); ?>
	</a>
</div>
<br/>
<br/>
<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger pull-left'
    ), 'dismiss');

?>
<a class="btn btn-success pull-right btnSiteUpdate"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscms_template_save'); ?></a>
<script type="text/javascript">
    $(document).ready(function() {
        var message = '<div class=\"pdc-content border-bottom modal-form-text-fix\" style=\"padding-top: 15px;\"></div><div class=\"pdc-content modal-form-text-fix\" style=\"padding-top : 5px;\"><p class=\"modal-text-info\">' + '<?= $this->translate('tr_meliscms_tool_site_info2') ?>' + '</p></div>';
    	$('#siteEditionForm fieldset div:nth-child(4)').closest('div').append(message);
	});
</script>