<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<style>
.site-info-modal th, .site-info-modal td{
    padding-right: 15px;
    padding-bottom: 10px;
}
.site-info-modal{
	margin-top: 20px;
}
</style>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons pencil" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_meliscms_tool_site_new_site') ?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                            		<?php if (!empty($this->sitePages)){?>
                            			<h3><b><?php echo $this->sitePages->site_name ?></b> <?php echo $this->translate('tr_meliscms_tool_site_site_created_title')?></h3>
                            			<div class="alert alert-warning site-info-modal">
                            				<p><?php echo $this->translate('tr_meliscms_tool_site_site_created_message')?></p>
                            			</div>
                                        <table class="site-info-modal">
                                        	<tbody>
                                        		<tr>
                                        			<th><?php echo $this->translate('tr_meliscms_tool_site_site_name')?></th>
                                        			<td><?php echo $this->sitePages->site_id.' - '.$this->sitePages->site_name ?></td>
                                        		</tr>
                                        		<tr>
                                        			<th><?php echo $this->translate('tr_meliscms_tool_site_site_module')?></th>
                                        			<td>/module/MelisSites/<?php echo $this->sitePages->site_name ?> </td>
                                        		</tr>
                                        		<tr>
                                        			<th><?php echo $this->translate('tr_meliscms_tool_site_site_layout')?></th>
                                        			<td>/module/MelisSites/<?php echo $this->sitePages->site_name ?>/view/layout/defaultLayout.phtml</td>
                                        		</tr>
                                        		
                                        		<?php if (!empty($this->sitePages->pages[0])){?>
                                            		<tr>
                                            			<th><?php echo $this->translate('tr_meliscms_tool_site_homepage')?></th>
                                            			<td><?php echo $this->sitePages->pages[0]['page_id'].' - '.$this->sitePages->pages[0]['page_name'] ?> - /<?php echo $this->sitePages->site_name ?>/IndexController/index</td>
                                            		</tr>
                                        		<?php }?>
                                        		
                                        		
                                        		<?php if (!empty($this->sitePages->pages[1])){?>
                                            		<tr>
                                            			<th><?php echo $this->translate('tr_meliscms_tool_site_page_404')?></th>
                                            			<td><?php echo $this->sitePages->pages[1]['page_id'].' - '.$this->sitePages->pages[1]['page_name'] ?> - /<?php echo $this->sitePages->site_name ?>/Page404Controller/index</td>
                                            		</tr>
                                        		<?php }?>
                                        	</tbody>
                                        </table>
                                    <?php }?>
                            		<br>
                                 	<div align="right">
                                 		<a data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscore_notification_modal_Close')?></a>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
