<div id="siteeditalert"></div><!-- 
<p><label for="select_env">Select Environment: </label></p>
<select name="select_env" id="id_select_env" class="form-control"></select>
<hr/> -->
<div id="formsiteedit">
<span class="hidden" id="s404pid">this should be hidden</span>
<?php 
$form = $this->meliscms_site_tool_generic_form;
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();
?>
<div class="col-sm-12"><a href="#" class="small"  id="btnDelEnv"><i class="fa fa-times"></i> <?= $this->translate('tr_meliscms_tool_site_delete_env'); ?></a></div>
<br/><br/>

<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger pull-left'
    ), 'dismiss');

?>

<a class="btn btn-success pull-right btnSiteUpdate"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscms_template_save'); ?></a>


</div>