<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->siteId . '_' . $this->zoneconfig['conf']['id'] . '"';
}

$data_melisKey = $this->melisKey;
?>
<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
    <div class="spacing-x2 innerAll">
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="pull-left"><?= $this->translate('tr_melis_cms_sites_tool_languages_title'); ?></h3>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="pull-left"><?= $this->translate('tr_melis_cms_sites_tool_languages_question1'); ?></h3>
                </div>
            </div>
        </div>
        <?php
            $form = clone $this->form;
            $form->prepare();

            echo $this->form()->openTag($form);
        ?>
        <!--LANGUAGES LISTING-->
        <input type="text" class="to-delete-languages-data" name="to_delete_languages_data" value="false" hidden="hidden">
        <?php foreach ($this->availableLangs as $language) { ?>
            <label class="checkbox-inline">
                <?php
                    $checked = '';
                    $active = '';

                    if (in_array($language['lang_cms_id'], $this->activeLangs)) {
                        $checked = 'checked';
                        $active = 'active';
                    }
                ?>
                <input type="checkbox" class="sites-tool-lang-tab-checkbox" name="slang_lang_id[]" data-active="<?= $active ?>" value="<?= $language['lang_cms_id'] ?>" <?= $checked ?>> <?= $language['lang_cms_name'] ?>
            </label>
        <?php } ?>
        <!--LANGUAGES LISTING END-->
        <br>
        <br>
        <h3><?= $this->translate('tr_melis_cms_sites_tool_languages_question2'); ?></h3>
        <!-- SITE OPTION LANGUAGE URL -->
        <?php
            $option1 = '';
            $option2 = '';

            if ($this->siteOptLangUrl == 1) {
                $option1 = 'checked';
            } else {
                $option2 = 'checked';
            }
        ?>
        <div class="row">
            <div class="col-md-12">
                <label class="radio-inline">
                    <input type="radio" class="radio" name="site_opt_lang_url" value="2" <?= $option2 ?>> <?= $this->translate('tr_melis_cms_sites_tool_languages_option2'); ?>
                </label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label class="radio-inline">
                    <input type="radio" class="radio" name="site_opt_lang_url" value="1" <?= $option1 ?>> <?= $this->translate('tr_melis_cms_sites_tool_languages_option1'); ?>
                </label>
            </div>
        </div>
        <!-- SITE OPTION LANGUAGE URL END -->
        <?php
            echo $this->form()->closeTag();
        ?>
    </div>
</div>