<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->siteId . '_' . $this->zoneconfig['conf']['id'] . '"';
}

$data_melisKey = $this->melisKey;
?>
<?php if(!empty($this->siteId)) { ?>
<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
    <div class="spacing-x2 innerAll">
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="float-left"><?= $this->translate('tr_melis_cms_sites_tool_languages_title'); ?></h3>
                </div>
            </div>
        </div>
        <br>
        <br>
        <?php
            $form = clone $this->form;
            $form->prepare();

            echo $this->form()->openTag($form);
        ?>
        <!--LANGUAGES LISTING-->
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-12">
                    <legend class="float-left" style="margin-bottom: -10px;"><?= $this->translate('tr_melis_cms_sites_tool_languages_question1'); ?></legend>
                </div>
            </div>
        </div>
        <div class="row sites-language">
            <?php foreach ($this->availableLangs as $language) { ?>
                <?php
                    $checked = '';
                    $active = '';

                    if (in_array($language['lang_cms_id'], $this->activeLangs)) {
                        $checked = 'checked';
                        $active = 'active';
                    }
                ?>
                <div class="col-md-2">
                    <div class="row">
                        <div class="checkbox">
                            <div class="checkbox cb-cont" style="position:relative;">
                                <label class="remember-me-cont">
                                    <span class="cbmask-outer clearfix">
                                        <span class="cbmask-inner cb-modules-mask <?php echo $checked ? 'cb-active' : '';  ?>"></span>
                                    </span>
                                    <input type="checkbox" class="sites-tool-lang-tab-checkbox" id="cms-sites-lang-checkbox-<?= $language['lang_cms_id'] ?>" name="slang_lang_id[]" data-active="<?= $active ?>" value="<?= $language['lang_cms_id'] ?>" <?= $checked ?>>
                                    <input type="text" class="sites-tool-lang-tab-checkbox-lang" name="to_delete_languages_data[<?= $language['lang_cms_id'] ?>]" value="false" hidden="hidden">
                                </label>
                                <span><?= $language['lang_cms_name'] ?></span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <!--LANGUAGES LISTING END-->
        <br>
        <?php
            echo $this->melisFieldCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
<?php } ?>