-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 20:33:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_gdpr_texts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_gdpr_texts` ;

CREATE TABLE IF NOT EXISTS `melis_cms_gdpr_texts` (
  `mcgdpr_text_id` INT NOT NULL AUTO_INCREMENT,
  `mcgdpr_text_site_id` INT NOT NULL,
  `mcgdpr_text_lang_id` INT NOT NULL,
  `mcgdpr_text_value` LONGTEXT NOT NULL,
  PRIMARY KEY (`mcgdpr_text_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
