	// Editor the will use for Pages
	melisTinyMCE.createTinyMCE("html", "div.html-editable", {templates: '/melis/MelisCms/PageEdition/getTinyTemplates?idPage=<?php echo $this->idPage; ?>'});
	melisTinyMCE.createTinyMCE("textarea", "div.textarea-editable");
	melisTinyMCE.createTinyMCE("media", "div.media-editable");
	
	
	// run this function when you click out of the tinymce
	$("body").on("blur", ".melis-editable", function(){

        // get all data-attributes from the clicked
        var currentdata = $(this).data();

        // get the content of the active tinyMCE editor.
        var content = tinyMCE.activeEditor.getContent({format : 'html'});

        var data = {
            tagId : currentdata.tagId,
            tagValue : content,
        };
        disableCmsButtons();
        $.post("/melis/MelisCms/PageEdition/savePageTagSession?idPage="+currentdata.idPage,
            data,
            function(data, status){
            enableCmsbuttons();
        });
	});
	
		
	// OPENING THE POPUP
	$("body").on("click", ".mce-btn", function(){
		
		var mcePopUp = $("#mce-modal-block").length;
		if(mcePopUp){

			// iframe height
			var iframeHeight = $(window).height();
				
			// dialog box height
			var dialogHeight = $(".mce-window").outerHeight();
			
			parent.scrollToViewTinyMCE(dialogHeight, iframeHeight);
			
			// CLOSING THE POPUP
			var timeOut = setInterval(function(){ 
			
				// console.log( "return =" + parent.scrollOffsetTinyMCE() );
				if( !$(".mce-window").is(":visible") ){
				// window.parent.scrollTo( 0,parent.scrollOffsetTinyMCE())
					window.parent.$("body").animate({scrollTop: parent.scrollOffsetTinyMCE() }, 200);
					
					clearTimeout(timeOut);
				}
			}, 300);
			
		}
		else{
			/* console.log("no popup"); */
		}
		
	});

    function disableCmsButtons()
    {
        window.parent.$("div.make-switch label on, off").parent().css("z-index", -1).parents("div.make-switch").css("opacity", 0.5);
        window.parent.$("div[data-melisKey='meliscms_page_actions']").find("a").attr("disabled", "disabled").click(false);
    }

    function enableCmsbuttons()
    {
        window.parent.$("#<?php echo $this->idPage; ?>_id_meliscms_page_action_tabs").removeClass('relative');
        window.parent.$("#<?php echo $this->idPage; ?>_id_meliscms_page_action_tabs li.btn-disabled").remove();
        window.parent.$("div.make-switch label on, off").parent().css("z-index", 1).parents("div.make-switch").css("opacity", 1);
    }

    enableCmsbuttons();
	

