<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
	
?>
<div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="bg-white innerAll transition3ms">
	<ul id="<?= $this->idPage; ?>_id_meliscms_page_action_tabs" class="menubar menu-bar-options">
		<?php 
		if (!empty($this->zoneconfig['interface']))
		{
			foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
			{
				if(!in_array($keyConfig, $this->exclude)) {
					echo $this->$keyConfig;
				}

			}
		}
		?>
	</ul>
</div>
<?php if($this->page_tpl_id != -1 && $this->idPage != 0){?>
<script type="text/javascript">
    if(jQuery !== undefined) {
        melisCms.disableCmsButtons(<?= $this->idPage ?>);
    }
</script>
<?php }?>