<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<li<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
	<a class="btn btn-default melis-savepage" data-pagenumber="<?= $this->idPage; ?>" data-fatherpageid="<?= $this->idFatherPage; ?>">
	    <span class="fa fa-save"></span>
		<span><?php echo $this->translate('tr_meliscms_page_actions_draft') ?></span>
	</a>
</li>