<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="page-content-container iframe-container">
	<div class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
		<div class="widget-head nav">
			<ul class="tabs-label nav-tabs nav">
				<?php
					if (!empty($this->zoneconfig['interface']))
					{

                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
						{
                            if(!in_array($keyConfig, $this->exclude)) {

							$id = '';
							if (!empty($menuConfig['conf']['id']))
								$id = ' id="' . $this->idPage . '_' . $menuConfig['conf']['id'] . '_title"';

							$tabname = 'Tab';
							if (!empty($menuConfig['conf']) && !empty($menuConfig['conf']['name']))
								$tabname = $menuConfig['conf']['name'];

							$icon = '';
							if (!empty($menuConfig['conf']) && !empty($menuConfig['conf']['icon']))
								$icon = $menuConfig['conf']['icon'];

							?>
							<li class="nav-item">
								<a class="nav-link glyphicons <?= $icon; ?>" data-page-id="<?= $this->idPage ?>" data-bs-toggle="tab" href="#<?= $this->idPage; ?>_<?= !empty($menuConfig['conf']['id']) ? $menuConfig['conf']['id'] : ''; ?>">
									<i> </i>
									<span><?= $tabname; ?></span>
								</a>
							</li>
							<?php
                            }
						}
					}
				?>
			</ul>
		</div>
		<div class="widget-body tab-content">
		<?php
			if (!empty($this->zoneconfig['interface']))
			{
				foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
				{
					echo $this->$keyConfig;
				}
			}
		?>
		</div>
	</div>
</div>

