<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="page-head-container">
	<?php 
		if (!empty($this->zoneconfig['interface']))
		{
			foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
			{ 
				echo $this->$keyConfig;
			}
		}
	?>
</div>