<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<li<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="dropdown">

    	<a href="#" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown">
        	<span class="fa fa-eye"></span> 
			<?php echo $this->translate('tr_meliscms_page_actions_See') ?>
        	<span class="caret"></span>
    	</a>
    	<ul class="dropdown-menu">
    		<?php 
				if (!empty($this->zoneconfig['interface']))
				{
					foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
					{ 
						echo $this->$keyConfig;
					}
				}
			?>
    	</ul>

</li>