<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
	
	// check the status of the page
	$status = ( $this->currentStatus ) ? 'checked' : '';
?>

<li<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' >
	<div data-pagenumber="<?= $this->idPage; ?>" class="make-switch page-publishunpublish" data-on-label="<?= $this->translate('tr_meliscms_page_published_text'); ?>" data-off-label="<?= $this->translate('tr_meliscms_page_unpublished_text'); ?>" data-text-label="<?= $this->translate('tr_meliscms_page_status_text'); ?>">
        <input type="checkbox" data-pagenumber="<?= $this->idPage; ?>" <?= $status; ?>>
    </div>
</li>
 
