<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<li<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
	<a class="" href="/id/<?= $this->idPage; ?>/preview?melisSite=<?= $this->namespace; ?>" target="_blank">
	    <span class="fa fa-eye"></span>
		<span><?php echo $this->translate('tr_meliscms_page_actions_Preview') ?></span>
	</a>
</li>