<div id="<?= $this->pluginId; ?>" class="melis-cms-gdpr-banner-container">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <p>
                <?= $this->bannerContents; ?>
                <a class="btn btn-success gdpr-banner-agree" data-gdpr-banner-plugin-id="<?= $this->pluginId; ?>"
                   href="javascript:void(0)"><?= $this->translate($this->labels['agree']); ?>
                </a>
            </p>
        </div>
    </div>
</div>
<?php if ($this->renderMode === 'melis'): ?>
    <pre><?= $this->labels['pluginLoaded']; ?></pre>
<?php endif; ?>
<script type="text/javascript">
    (function () {
        lookForJquery(melisCmsGdprBanner);

        function lookForJquery(fn) {
            if (window.jQuery && typeof fn === 'function' && fn !== null && typeof MelisCmsGdprBanner !== 'undefined') {
                fn();
            }
            else {
                setTimeout(function () {
                    lookForJquery(fn)
                }, 50);
            }
        }

        function melisCmsGdprBanner() {
            let bannerCookie = MelisCmsGdprBanner.getCookie(MelisCmsGdprBanner.getCookieName);

            if (bannerCookie === undefined) {
                /** User's first visit: Declare banner cookie for this site */
                MelisCmsGdprBanner.setCookie(MelisCmsGdprBanner.getCookieName, true);
                bannerCookie = true;
            }

            let banner = $("#<?= $this->pluginId; ?>");
            if (bannerCookie) {
                banner.show();
            }
        }
    })();
</script>
