<h1>sdlfjdsf</h1>
<?php
    $id = $this->idPage.'_'.$this->zoneconfig['conf']['id'];
    $data_melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<?php if (!empty($this->pageInfo)){?>
    <div class="widget" id="<?= $id; ?>" data-melisKey='<?= $data_melisKey; ?>'>
        <div class="widget-body padding-none">
            <div class="bg-white margin-none">
                <h4 class="pagelang-title"> <?php echo $this->pageInfo?></h4>
            </div>
        </div>
    </div>
<?php }?>
