<?php
    $id = $this->idPage.'_'.$this->zoneconfig['conf']['id'];
    $data_melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<div class="col-xs-12 col-md-6">
    <div class="widget" <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
        <div class="widget-body padding-none">
            <div class="bg-white margin-none">
                <h4 class="pagelang-title"><?php echo $this->translate('tr_meliscms_page_lang_create_form')?></h4>
                <?php
                    $form = $this->createPageLangform;
                    $form->prepare();
                    $form->setAttribute('id', $this->idPage.'_'.$form->getAttribute('id'));
                    $formId = $form->getAttribute('id');
                    $form->get('pageLangLocale')->setAttribute('class', 'dropdown-lang');
                    echo $this->form()->openTag($form);
                    echo $this->formRow($form->get('pageLangPageId'));
                ?>
                    <div class="dropdown-lang-box">
                        <?php 
                            $form->get('pageLangLocale')->setLabel('');
                            echo $this->formRow($form->get('pageLangLocale'));
                        ?>
                        <div class="form-group">
                            <button type="button" class="btn btn-success pull-right pageLangCreate" data-pageid="<?php echo $idPage?>" data-formid="<?php echo $formId?>"><?php echo $this->translate('tr_meliscms_page_lang_create_btn')?></button>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag($form);?>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        var langlists = $('select.dropdown-lang');
        $('div.loadAttrCont').hide();
        langlists.fadeIn();
        langlists.select2({
            placeholder: translations.tr_meliscms_page_lang_choose_opt,
            templateResult: formatState,
        });
        $("langlists").next(".select2").addClass("select-lang");
        function formatState (state) {
            if (!state.id) {
                return state.text;
            }
            var baseUrl = "/MelisCms/images/lang-flags/";
            var $state = $(
                '<span><img src="' + baseUrl + '/' + state.element.value.toLowerCase() + '.png" class="img-flag" /> ' + state.text + '</span>'
            );
            return $state;
        };
    });
</script>