<div id="templateaddformalert"></div>
<?php 
$form = $this->meliscms_tool_template_add;
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();
?>


<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger pull-left'
    ), 'dismiss');

?>

<a href="#modal-template-manager-actions" class="btn btn-success pull-right" onclick="toolTemplate.addNewTemplate()" id="btnTemplateAdd"><i class="fa fa-plus"></i>  <?= $this->translate('tr_meliscms_template_add'); ?></a>