<?php 
$id = $this->zoneconfig['conf']['id'];
$openAddNewTemplateButton = $this->melisModalInvoker()->render(array(
    'id' => $id,
    'href' => '#modal-template-manager-actions',
    'class' => 'btn btn-success',
    'text' => '<i class="fa fa-plus"></i> '.$this->translate('tr_tool_templates_button_text_add'),
    'onclick' => "melisCoreTool.showOnlyTab('#modal-template-manager-actions', '#id_modal_tool_template_add');",
    'data-melisKey' => $this->melisKey,
), 'invoke');
echo $openAddNewTemplateButton;

?>