<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

?>
<div class="modal-content" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons notes" data-toggle="tab" aria-expanded="true"><i></i>
                                Export Pages
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" id="<?= $id ?>">
                            <div class="page-export-container">
                                <?php if($this->isAdmin) { ?>
                                    <div class="page-export-form">
                                        <?php
                                        $form = $this->exportForm;
                                        $form->prepare();

                                        foreach ($form->getElements() as $element => $attributes) {
                                            $el = $form->get((string) $element);

                                            if ($el->getName() == 'page_export_type') {
                                                $el->setValue('1');
                                            }
                                        }

                                        echo $this->form()->openTag($form);
                                        echo $this->melisFieldCollection($form);
                                        echo $this->form()->closeTag();
                                        ?>
                                    </div>
                                    <div class="page-export-progress hidden">
                                        <span><?= $this->translate('tr_melis_cms_tree_export_in_progress')?> ...(<prog_percent></prog_percent>%)</span>
                                        <div class="progress">
                                            <div id="exportImportProgressbar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                            </div>
                                        </div>
                                    </div>
                                <?php } else { ?>
                                    <div class="user-no-rights">
                                        <p>
                                            <?= $this->translate('tr_melis_cms_tree_export_no_rights'); ?>
                                        </p>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                    <div align="right">
                        <button type="button" data-dismiss="modal" class="btn btn-danger pull-left"><?php echo $this->translate('tr_meliscms_tool_sites_cancel')?></button>
                        <button type="button" class="btn btn-success" id="btn-export-pages" <?= (!$this->isAdmin) ? 'disabled="true"' : ''?>>Export</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
