<?php
if (!function_exists('displayMenuPlugin')) {
    function displayMenuPlugin($moduleName, $pluginName, $pluginConf, $siteModule)
    {
        $conf = $pluginConf['melis'];
        if (!empty($conf['thumbnail']))
            $thumbnail = $conf['thumbnail'];
        else
            $thumbnail = '/MelisFront/plugins/images/default.jpg';

        if (!empty($conf['name'])) {
            $name = $conf['name'];
        } else {
            $name = $pluginName;
        }
        ?>
        <?php
        if (isset($conf['subcategory']['id'])) {
            $pluginid = $conf['subcategory']['id'];
            /**
             * check if plugin is came from the mini template
             * to remove the thumbnail
             */
            if (strpos($pluginid, 'miniTemplatePlugins') !== false) { ?>
                <div class="melis-cms-plugin-snippets plugins-override-padding" data-module-name="<?= $moduleName; ?>"
                     data-plugin-name="<?= $pluginName; ?>" data-plugin-site-module="<?= $siteModule ?>"
                     title="<?php if (!empty($conf['description'])) {
                         echo $conf['description'];
                     } ?>">
                    <span class="melis-cms-plugin-title plugins-name-override-margin"><?= $name; ?></span>
                </div>
            <?php } else { ?>
                <div class="melis-cms-plugin-snippets" data-module-name="<?= $moduleName; ?>"
                     data-plugin-name="<?= $pluginName; ?>" data-plugin-site-module="<?= $siteModule ?>"
                     title="<?php if (!empty($conf['description'])) {
                         echo $conf['description'];
                     } ?>">
                    <img src="<?= $thumbnail; ?>" alt="">
                    <span class="melis-cms-plugin-title"><?= $name; ?></span>
                </div>
            <?php }
        } else { ?>
            <div class="melis-cms-plugin-snippets" data-module-name="<?= $moduleName; ?>"
                 data-plugin-name="<?= $pluginName; ?>" data-plugin-site-module="<?= $siteModule ?>"
                 title="<?php if (!empty($conf['description'])) {
                     echo $conf['description'];
                 } ?>">
                <img src="<?= $thumbnail; ?>" alt="">
                <span class="melis-cms-plugin-title"><?= $name; ?></span>
            </div>
        <?php }
        ?>
        <?php
    }
}
?>
<?php
$ctrNewPlugins = 0;
$sectionHasNewPlugins = $this->sectionNewPlugins ?? [];
?>
<div class="melis-cms-dnd-box">
    <div class="melis-cms-dnd-fix-menu">
        <div id="cmsPluginsMenuLoader">

        </div>
        <div id="cmsPluginsMenuContent">
            <!--        loads content here-->
        </div>
    </div>
    <div id="melisPluginBtn">
        <?php if (!empty($sectionHasNewPlugins) ) : ?>
            <?php
            // latesplugin installed
            $latestPlugin = $this->latestPlugin;
            $latestPluginDatetime = $latestPlugin['latest_plugin_datetime'];
            $dateTimeElapse = date('Y-m-d h:i:s',strtotime("+" . $this->newPluginNotification . " days",strtotime($latestPluginDatetime)));
            $dateToday      = date('Y-m-d h:i:s');
            ?>
            <?php if ($dateToday < $dateTimeElapse) : ?>
                <span class="melis-templating-new-plugin">
                    <span class="new-plugin-indicator">NEW!</span>
                </span>
            <?php endif ?>
        <?php endif ?>
        <i class="fa fa-plug"></i>
    </div>
</div>


<!--  ======================= tinymce temp CSS ============================= -->
<link rel="stylesheet" href="/MelisCms/css/jquery-ui.css">
<link rel="stylesheet" href="/MelisCms/css/plugin-mini-menu.css">
<link rel="stylesheet" href="/MelisCms/css/dragndrop.css">
<link rel="stylesheet" href="/MelisCms/css/dynamic-dragndrop/dynamic-dragndrop.css?v=<?= time(); ?>">
<link href="/assets/css/schemes.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/MelisCms/js/dragndrop/jquery-ui.js"></script>
<script type="text/javascript" src="/MelisCms/js/dragndrop/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="/MelisCms/js/plugins/plugin.sortable.js"></script>
<script type="text/javascript" src="/MelisCms/js/dragndrop/dragndrop.js"></script>
<script type="text/javascript" src="/MelisCms/js/dragndrop/dynamic-dragndrop.js?v=<?= time(); ?>"></script>