<div
    id="<?= $this->zoneconfig['conf']['id'] ?>"
    class="me-heading bg-white border-bottom"
    data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>"
>
    <div class="row">
        <div class="me-hl col-xs-12 col-sm-8 col-md-9">
            <h1 class="content-heading">Add Mini-Template</h1>
            <p>creates a mini-template</p>
        </div>
        <div class="me-hr col-xs-12 col-sm-4 col-md-3">
            <?php if ($this->formType == 'create') : ?>
                <button class="btn btn-success" id="melis-cms-minitemplate-add-btn">
                    <i class="fa fa-plus"></i>
                    Create
                </button>
            <?php else: ?>
                <button class="btn btn-success" id="melis-cms-minitemplate-edit-btn">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            <?php endif; ?>
        </div>
    </div>
</div>