<!DOCTYPE html>
<html lang="en">
	<head>
      	<title>SiteSample</title>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<div id="content">
			<?= $this->content; ?>
		</div>
		<div id="footer">
	        <!-- Datas Page : 
			idPage = <?= $this->idPage; ?> /
			pageLangId = <?= $this->pageLangId; ?> /
			pageLangLocale = <?= $this->pageLangLocale; ?> /
			renderType = <?= $this->renderType; ?> /
			renderMode = <?= $this->renderMode; ?>
			-->
		</div>
	</body>
</html>