<html>
	<head>
		<?= $this->headTitle('SiteSample'); ?>
		<?= $this->headLink()->appendStylesheet('/SiteSample/css/styles.css'); ?>
	</head>
	<body>
		<div id="content">
			<?= $this->content; ?>
		</div>
		<div id="footer">
	<!-- 		Datas Page : 
			idPage = <?= $this->idPage; ?> /
			pageLangId = <?= $this->pageLangId; ?> /
			pageLangLocale = <?= $this->pageLangLocale; ?> /
			renderType = <?= $this->renderType; ?> /
			renderMode = <?= $this->renderMode; ?>
			 -->
		</div>
		<script type="text/javascript" src="/MelisCore/assets/components/library/jquery/jquery.min.js?v=v1.2.3"></script>
	</body>
</html>