<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $id ?>" class="glyphicons <?php echo ($this->s301Id) ? 'pencil' : 'plus' ?>" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate($this->title) ?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                            		<p class="modal-text-info"><?= $this->translate('tr_meliscms_tool_site_301_s301_modal_info'); ?></p>
                                    <?php
                                    	$form = $this->meliscms_tool_site_301_generic_form;
                                    	$form->prepare();
                                    	echo $this->form()->openTag($form); 
                                    	echo $this->melisFieldCollection($form);
                                    	echo $this->form()->closeTag(); 
                                    ?>
                                 	<div align="right">
                                 		<a data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscms_common_close')?></a>
                                 		<a class="btn btn-success saveSiteRedirect" data-s301id="<?php echo $this->s301Id?>"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscore_tool_gen_save'); ?></a>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
