<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
	
?>
<div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="tab-pane widget-body-regular meliscms_center_tabs">
	<iframe scrolling="no" data-iframe-id="<?= $this->idPage; ?>" onload="melisCms.iframeLoad();" class="melis-iframe" src="/id/<?= $this->idPage; ?>/renderMode/melis?melisSite=<?= $this->namespace; ?>"></iframe>
</div>