<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
$data_melisKey = 'data-melisKey="' . $this->melisKey . '"';
?>
<div class="modal-content">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#<?= $id ?>" class="glyphicons <?= ($this->pids_id) ? 'pencil' : 'plus' ?>"
                              data-toggle="tab" aria-expanded="true"><i></i> <?= $this->translate($this->tabTitle) ?></a>
                        </li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" <?= $id ?>>
                            <div id="cmsPlatformAlert"></div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php if (!empty($this->available_platform) || !empty($this->pids_id)): ?>
                                        <p class="modal-text-info"><?= $this->translate('tr_meliscms_tool_platform_modal_info') ?> </p>
                                        <?php
                                            $form = $this->meliscms_tool_platform_generic_form;
                                            $form->prepare();
                                            echo $this->form()->openTag($form);
                                            echo $this->melisFieldCollection($form);
                                            echo $this->form()->closeTag();
                                        ?>
                                        <div align="right">
                                            <a data-dismiss="modal" class="btn btn-danger pull-left"><i
                                                        class="fa fa-times"></i> <?= $this->translate('tr_meliscms_common_close') ?>
                                            </a>
                                            <a class="btn btn-success btnSavePlatfomrRange"
                                               data-id="<?= $this->pids_id ?>"><i
                                                        class="fa fa-save"></i> <?= $this->translate('tr_meliscms_platform_id_save'); ?>
                                            </a>
                                        </div>
                                    <?php else: ?>
                                        <div class="alert alert-info">
                                            <?= $this->translate('tr_meliscms_tool_platform_modal_info_assigned_page_ids'); ?>
                                        </div>
                                        <div align="right">
                                            <a data-dismiss="modal" class="btn btn-danger pull-left">
                                                <i class="fa fa-times"></i> <?= $this->translate('tr_meliscms_common_close') ?>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
