<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

?>
<div class="modal-content pageImportModal" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>" data-pageid="<?= $this->pageId ?>" data-pagename="<?= $this->pageName ?>">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="nav-item active">
                            <a data-bs-target="#<?php echo $this->zoneconfig['conf']['id'] ?>" href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons notes" data-bs-toggle="tab" aria-expanded="true"><i></i>
                                <?= $this->translate('tr_melis_cms_page_tree_import') ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div id="importPageForm" class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active">
                            <?php if ($this->isAdmin) : ?>
                                <input type="text" id="page-import-max-file-size" value="<?= $this->max_size ?>" hidden>
                                <div>
                                    <?php
                                    $form = $this->importForm;
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    ?>

                                    <!-- Checkbox -->
                                    <div class="checkbox">
                                        <div class="checkbox cb-cont page-import-cont">
                                            <label class="remember-me-cont">
                                                <span class="cbmask-outer clearfix">
                                                    <span class="cbmask-inner cb-modules-mask cb-active"></span>
                                                </span>
                                                <input type="checkbox" name="keepIds" value="1" checked>
                                            </label>
                                            <span id="page-import-checkbox-span"><?= $this->translate('tr_melis_cms_page_tree_import_keep_ids') ?></span>
                                            <i class="fa fa-info-circle fa-lg pull-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_melis_cms_page_tree_import_modal_keep_ids_tooltop'); ?>" aria-describedby="tooltip422018" style="margin-top: -3px; margin-right: -18px; font-size: 17px;"></i>
                                        </div>
                                    </div>
                                    </br>

                                    <!-- End Checkbox -->

                                    <?php
                                    echo $this->melisFieldCollection($form);
                                    echo $this->form()->closeTag();
                                    ?>
                                    <div id="pageImportConsole" style="height: 400px; border: 1px #e61c23 solid; padding: 5px; margin-bottom: 8px; overflow-y: scroll;display: none;">
                                    </div>
                                </div>
                            <?php else : ?>
                                <div>
                                    <p><?= $this->translate('tr_melis_cms_tree_import_import_not_admin1') ?></p>
                                    <p><?= $this->translate('tr_melis_cms_tree_import_import_not_admin2') ?></p>
                                    </br>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div align="right">
                        <?php if ($this->isAdmin) : ?>
                            <button type="button" id="test-btnbtn" data-bs-dismiss="modal" class="btn btn-danger pull-left"><?php echo $this->translate('tr_meliscms_tool_sites_cancel')?></button>
                            <button type="button" class="btn btn-success" id="page-tree-import-test" disabled><?= $this->translate('tr_melis_cms_page_tree_import_modal_test_file'); ?></button>
                        <?php else : ?>
                            <button type="button" data-bs-dismiss="modal" class="btn btn-danger pull-left"><?php echo $this->translate('tr_meliscms_tool_sites_cancel')?></button>
                            <div style="display: block; clear: both;"></div>
                        <?php endif; ?>
                    </div>
                </div>
                <div id="importPageValidated" class="widget-body innerAll inner-2x" style="display: none;">
                    <div class="tab-content">
                        <div class="tab-pane active">

                        </div>
                    </div>
                    <div align="right" class="btn-container" style="margin-top: 15px;">

                    </div>
                </div>
                <div id="importPageDone" class="widget-body innerAll inner-2x" style="display: none;">
                    <div class="tab-content">
                        <div class="tab-pane active">
                            <div class="main-error">

                            </div>
                            <div id="pageImportDoneConsole" style="height: 300px; border: 1px #e61c23 solid; padding: 5px; margin-bottom: 8px; overflow-y: scroll;display: none;">
                            </div>
                        </div>
                    </div>
                    <div class="btn-container" style="margin-top: 15px; padding: 15px;">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
