<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
$data_melisKey = $this->melisKey;

?>
<div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="tab-pane clearfix">
    <div class="col-md-12">
        <div class="widget row widget-inverse">
            <div class="widget-body">
                <div class="tab-content innerAll spacing-x2">
                    <?php
                    if (!empty($this->zoneconfig['interface'])) {
                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                            echo $this->$keyConfig . ' ';
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
