<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = 'id="' . $this->zoneconfig['conf']['id'] . '"';
}
$data_melisKey = $this->melisKey;
?>
<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>" class="mcms-gdpr-banner-header bg-white">
    <div class="row">
        <div class="col-md-12">
            <?php
            echo $this->form()->openTag($this->form);
            echo $this->melisFieldCollection($this->form);
            echo $this->form()->closeTag();
            ?>
            <a class="btn btn-success cms-gdpr-save float-right" title="<?= $this->label['saveBtn']; ?>" style="display: none;">
                <i class="fa fa-save"></i> <?= $this->label['saveBtn']; ?>
            </a>
            <script type="text/javascript">
                (function () {
                    var siteSelector = $body.find(".cms_gdpr_banner_site_filter_form #id_mcgdprbanner_site_id");
                    if (siteSelector.length > 0) {
                        siteSelector.select2({
                            minimumResultsForSearch: -1,
                            placeholder: translations.tr_melis_cms_gdpr_banner_site_select
                        });
                    }
                })();
            </script>
        </div>
    </div>
</div>
