<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = 'id="' . $this->zoneconfig['conf']['id'] . '"';
}
$data_melisKey = $this->melisKey;
?>
<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>" class="mcms-gdpr-banner-header bg-white">
    <div class="row">
        <div class="mcms-gdpr-banner-desc col-md-12">
            <p><?= $this->label['toolDesc']; ?></p>
            <a class="btn btn-success cms-gdpr-save pull-right" title="<?= $this->label['saveBtn']; ?>"><i class="fa fa-save"></i> <?= $this->label['saveBtn']; ?></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
            echo $this->melisFieldCollection($this->form);
            $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
