<div id="languagealert"></div>
<p class="modal-text-info"><?= $this->translate('tr_meliscms_tool_modal_text'); ?></p>
<div id="languageadd">
<?php 
$form = $this->meliscms_tool_language_generic_form; 
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();

echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger float-left'
    ), 'dismiss');
?>

<a class="btn btn-success float-right" id="btnLangCmsAdd"><i class="fa fa-plus"></i>  <?= $this->translate('tr_meliscms_common_add'); ?></a>
</div> 