<div id="langeditalert"></div>
<span id="platformupdateid" class="hidden"></span>
<div id="formplatformedit">
<?php 
$form = $this->meliscms_tool_language_generic_form;
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();

echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger pull-left'
    ), 'dismiss');
?>

<a class="btn btn-success pull-right" id="btnLangEdit"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscms_tool_language_forms_button_edit'); ?></a>
</div>