<div id="langeditalert"></div>
<span id="platformupdateid" class="hidden"></span>
<p class="modal-text-info"><?= $this->translate('tr_meliscms_tool_modal_text'); ?></p>
<div id="formplatformedit">
<?php 
$form = $this->meliscms_tool_language_generic_form;
echo $this->form()->openTag($form);
echo $this->melisFieldCollection($form);
echo $this->form()->closeTag();

echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscms_common_close'),
        'class' => 'btn btn-danger float-left'
    ), 'dismiss');
?>

<a class="btn btn-success float-right" id="btnLangEdit"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscms_common_save'); ?></a>
</div>